source ./nu_scripts/custom-completions/cargo/cargo-completions.nu
source ./nu_scripts/custom-completions/git/git-completions.nu
source ./nu_scripts/custom-completions/nano/nano-completions.nu
source ./nu_scripts/custom-completions/rustup/rustup-completions.nu
source ./nu_scripts/custom-completions/winget/winget-completions.nu
source ./nu_scripts/custom-completions/auto-generate/completions/7z.nu
source ./nu_scripts/custom-completions/auto-generate/completions/7zr.nu
source ./nu_scripts/custom-completions/auto-generate/completions/dotnet.nu
source ./nu_scripts/custom-completions/auto-generate/completions/ffmpeg.nu
source ./nu_scripts/custom-completions/auto-generate/completions/ffplay.nu
source ./nu_scripts/custom-completions/auto-generate/completions/ffprobe.nu
source ./nu_scripts/custom-completions/auto-generate/completions/flac.nu
source ./nu_scripts/custom-completions/auto-generate/completions/fzf.nu
source ./nu_scripts/custom-completions/auto-generate/completions/gitk.nu
source ./nu_scripts/custom-completions/auto-generate/completions/hugo.nu
source ./nu_scripts/custom-completions/auto-generate/completions/jq.nu
source ./nu_scripts/custom-completions/auto-generate/completions/julia.nu
source ./nu_scripts/custom-completions/auto-generate/completions/lua.nu
source ./nu_scripts/custom-completions/auto-generate/completions/make.nu
source ./nu_scripts/custom-completions/auto-generate/completions/mkvextract.nu
source ./nu_scripts/custom-completions/auto-generate/completions/pandoc.nu
source ./nu_scripts/custom-completions/auto-generate/completions/patch.nu
source ./nu_scripts/custom-completions/auto-generate/completions/pg_dump.nu
source ./nu_scripts/custom-completions/auto-generate/completions/pg_dumpall.nu
source ./nu_scripts/custom-completions/auto-generate/completions/pg_restore.nu
source ./nu_scripts/custom-completions/auto-generate/completions/psql.nu
source ./nu_scripts/custom-completions/auto-generate/completions/pyenv.nu
source ./nu_scripts/custom-completions/auto-generate/completions/python.nu
source ./nu_scripts/custom-completions/auto-generate/completions/python2.nu
source ./nu_scripts/custom-completions/auto-generate/completions/python3.nu
source ./nu_scripts/custom-completions/auto-generate/completions/rustc.nu
source ./nu_scripts/custom-completions/auto-generate/completions/sass.nu
source ./nu_scripts/custom-completions/auto-generate/completions/vim.nu
source ./nu_scripts/custom-completions/auto-generate/completions/wireshark.nu
